---
title: "**COVID-19**"
author: "Emily Damone, Taylor Krajewski, Alex Quinter, Kushal Shah, Euphy Wu, Jonathan Zhang"
date: "4/22/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# **Introduction**
(Background on Covid and a short description of difficulties in making real-time predictions as well as why we wanted to do this project/what we hypothesized)

# **Project Goal**

To predict the number of new cases of Covid-19 a country can expect on a chosen day given that country's previous number of recorded cases and a few measurable variables specific to that country that may affect the spread of the virus.


# **Data**

## *Raw Data*


### Hopkin’s COVID-19 Data
(give brief description of dataset)

### World Bank Data
(give brief discussion and talk about decision to add this data as covariates in model)

### Global Health Index Data
(give brief discussion and talk about decision to add this data as covariates in model)

## *Data Processing*
(Data processing summary - should discuss joining Covid data with country data from the other sources mentioned above)

## *Finalized Data*
(give a peak at our final data - maybe pick a country or two and show the data we will use from that country in our model?)

# **Packaging**
(description of our R package - functions and datasets it holds)

# **Methods**

## *Poisson GLMM*

Let $y_{ij}$ be the number of new cases country $i$ has on day $j$. 

We assume that each $y_{ij} \sim Poisson(\lambda_{ij})$, where the mean and variance of $y_{ij}$ is assumed to be some $\lambda_{ij}$

Let the covariate vector pertaining to the $i^{th}$ countrh in the $j^{th}$ month be defined as $x_{ij} = (1, t_{ij}, t^2_{ij}, GHS, AgeGEQ65, UrbanPop)$.

We assume an intercept, $\beta_0$, in our model, and thus we have $\beta = (\beta_0, \beta_1, \beta_2, \beta_3, \beta_4, \beta_5, \beta_6)^T$.

We assumed counts can be modeled with a Poisson GLMM such that $log(\lambda_{ij})=x_{ij}\beta+\gamma_{i1}+\gamma_{i2}t_{ij} = x_{ij}\beta+z_{ij}\gamma_i$, where $b_i$ is a vector of unobserved country-level random effects. We assume that

$$\left(\begin{array}{cc}\gamma_{i1} \\\gamma_{i2}\end{array}\right) \sim N_2\bigg(\left(\begin{array}{cc}0 \\0\end{array}\right),\left(\begin{array}{cc}g_{11} & g_{12} \\g_{21} & g_{22}\end{array}\right)\bigg)$$

So, in our model, $\gamma_{i1}$ is the deviation of the $i^{th}$ country from the baseline number of new cases, which we have set to 50, and $\gamma_{i2}$ is the deviation of the $i^{th}$ country from the average effect of the covariates in our model on number of new cases.


As in all GLMMs, the random effects are unobservable. Therefore, in order to obtain the likelihood, we must integrate them out.

Thus, we must perform separate integrals for each $\left(\begin{array}{cc}\gamma_{i1} \\\gamma_{i2}\end{array}\right)$, which share the common distribution dtermined by $G=\left(\begin{array}{cc}g_{11} & g_{12} \\g_{21} & g_{22}\end{array}\right)$.

Thus, we write the likelihood:

$$L(\beta, G | y, \gamma)=\prod^{n}_{i=1}\bigg(\prod^{n_i}_{j=1}f(y_{ij}|\lambda_{ij})\bigg)\phi(\gamma_i | 0, G) = \prod^{n}_{i=1}\int\bigg[\bigg(\prod^{n_i}_{j=1}f(y_{ij}|\lambda_{ij})\bigg)\phi(\gamma_i|0,G)\bigg]d\gamma_i$$

and the log-likelihood:

$$l(\beta, G | y, \gamma)=\sum^{n}_{i=1}log\bigg[\int\bigg[\bigg(\prod^{n_i}_{j=1}f(y_{ij}|\lambda_{ij})\bigg)\phi(\gamma_i|0,G)\bigg]d\gamma_i\bigg]$$

where $f(y_{ij}|\lambda_{ij})$ is the Poisson PMF with mean $\lambda_{ij}$, as defined above, and $\phi(\gamma_i|0,G)$ is the bivariate Normal PDF with mean 0 and covariance matrix $G=\left(\begin{array}{cc}g_{11} & g_{12} \\g_{21} & g_{22}\end{array}\right)$.


We maximized this log-likelihood to obtain estimates for $\beta$ and $G$.

***Need to explain how we did this here!***

## *Machine Learning Method*
(describe machine learning method used)

## *Model Evaluation*
(describe how we evaluated our model prediction and include comparison of Module 2/Module 3 methods)

# **Results**

## *Poisson GLMM*

## *Machine Learning*

## *Comparison on Methods*

# **Discussion**
(give brief summary of what was shown in the results section and add in any subjective thoughts.)

## *Limitations*
(This could go on for pages - will try to focus on a brief description. Discussed including one or two plots, such as South Korea, to show some limitations)

# **References**
(add in any articles we referenced, websites where data came from, etc.)